In [1]:
import pandas as pd
import numpy as np
import json
# Opening JSON file
f = open('data.json',)
  
# returns JSON object as 
# a dictionary
data = json.load(f)

# Closing file
f.close()

In [2]:
%load_ext autoreload
%autoreload 2
import pipeline_entity_quote as pipeline

/Users/oooyyyzzz/opt/anaconda3/lib/python3.8/site-packages/gensim/similarities/__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)
[nltk_data] Error loading punkt: <urlopen error [Errno 61] Connection
[nltk_data]     refused>

In [3]:
result_dict_entity = {}
result_dict_entity = pipeline.get_training_features_entity_smalltrial()

Current Time = 17:38:02
Current Time = 01:45:45

In [4]:
result_df_entity = pd.DataFrame.from_dict(result_dict_entity)
result_df_entity

[nltk_data] Error loading punkt: <urlopen error [Errno 61] Connection
[nltk_data]     refused>

,204f5d99-c9de-4bce-ae2f-5e98085b4930,0526bd0d-41bb-43fe-bdc9-dabeea9dcfaa,33e5aa3f-af33-461d-9e51-16a552e6b985,d10f9f69-204a-422d-886d-ff59f787fe22,88ffc85f-b495-4f59-af53-08a92030f9b7,6c0221c9-f3c9-4f6b-800e-685e75b317c1,e10be83f-75b7-40f8-b041-5bbb9f3f6d77,d65803ad-3800-4a16-b02b-fef589314fab,c0823b0b-16ee-46e3-955e-1bfd50300c3e,7cc09e87-92e3-48c6-aa65-f96fe480f2b0,...,33c6f2e4-afc3-4481-a1fb-5932b673ffec,0314d0d8-3da3-46c3-bc89-97110eb9dc5f,180c7786-e898-4ed9-b332-b067d2e2bd84,2c473d5a-054a-40b4-bbf7-619f6b59bb23,981a3f25-22af-44ed-ab41-316981deacc8,8dd1f569-7c3f-43c4-9c26-1543d89e032c,7fca5388-231e-4206-a5b2-7d3cd765ba80,f351f646-e3de-4b17-a457-c32741aafda0,f2cb35b3-1f70-471e-8bae-207f157c6cdf,f346bff6-b54e-4c4d-8f5d-44c740bd8e3a
entity_dict,"{'PERSON': ['Dianne Primavera', 'Scott Helker'...","{'PERSON': ['Sherwin Gatchalian'], 'CARDINAL':...","{'PERSON': ['Juan Ponce Enrile', 'Leila de Lim...","{'PERSON': ['Ann Wang', 'Fidel Macauyag', 'Ang...","{'PERSON': ['Juan Ponce Enrile', 'Mike Navallo...","{'PERSON': ['sana makiisa', 'Isko Moreno', 'Al...","{'PERSON': ['Mikunog', 'Zhander Cayabyab', 'Ki...","{'PERSON': ['Juan Ponce Enrile', 'Fides Lim', ...","{'PERSON': ['Davao del Norte', 'Capt', 'Rodrig...","{'PERSON': ['Fides Lim', 'Kaya naman '', 'BuCo...",...,"{'PERSON': ['Mohamed Zaini Mazlan', 'Jalan Amp...","{'PERSON': ['Syazwani Mahmud', 'Gabungan Pembe...","{'GPE': ['para'], 'PERSON': ['sido más vigente...","{'PERSON': ['Dr Shirley Sze', 'Stephen Hahn'],...","{'PERSON': ['Mahathir', 'Mahathir Mohamad', 'M...","{'PERSON': ['Upendra Raghav', 'Jai Shri Ram', ...",{'GPE': ['Malaysia']},"{'PERSON': ['La', 'Díaz Ordaz', 'Ingreso Famil...","{'PERSON': ['Samar', 'de Diatagon', 'Después d...","{'PERSON': ['Senegal', 'Benin', 'Jon Temin'], ..."
entity_num,54,22,39,33,36,15,44,122,40,59,...,49,32,5,22,29,27,1,56,45,27
entity_type_num,9,8,7,8,8,7,7,12,9,7,...,7,9,3,6,9,5,1,11,6,10

In [5]:
result_df_entity.to_csv("entity_features.csv")

In [6]:
result_df_entity_t = result_df_entity.T

In [7]:
result_df_entity_t.to_csv("entity_features.csv")

In [8]:
result_df_entity_t

,entity_dict,entity_num,entity_type_num
204f5d99-c9de-4bce-ae2f-5e98085b4930,"{'PERSON': ['Dianne Primavera', 'Scott Helker'...",54,9
0526bd0d-41bb-43fe-bdc9-dabeea9dcfaa,"{'PERSON': ['Sherwin Gatchalian'], 'CARDINAL':...",22,8
33e5aa3f-af33-461d-9e51-16a552e6b985,"{'PERSON': ['Juan Ponce Enrile', 'Leila de Lim...",39,7
d10f9f69-204a-422d-886d-ff59f787fe22,"{'PERSON': ['Ann Wang', 'Fidel Macauyag', 'Ang...",33,8
88ffc85f-b495-4f59-af53-08a92030f9b7,"{'PERSON': ['Juan Ponce Enrile', 'Mike Navallo...",36,8
...,...,...,...
8dd1f569-7c3f-43c4-9c26-1543d89e032c,"{'PERSON': ['Upendra Raghav', 'Jai Shri Ram', ...",27,5
7fca5388-231e-4206-a5b2-7d3cd765ba80,{'GPE': ['Malaysia']},1,1
f351f646-e3de-4b17-a457-c32741aafda0,"{'PERSON': ['La', 'Díaz Ordaz', 'Ingreso Famil...",56,11
f2cb35b3-1f70-471e-8bae-207f157c6cdf,"{'PERSON': ['Samar', 'de Diatagon', 'Después d...",45,6
f346bff6-b54e-4c4d-8f5d-44c740bd8e3a,"{'PERSON': ['Senegal', 'Benin', 'Jon Temin'], ...",27,10